baseURL = "https://asfaqs.github.io/"
languageCode = "zh-tw"
defaultContentLanguage = "zh-tw"
defaultContentLanguageInSubdir = false

title = 'Academia Sinica FAQ'
theme = "hugo-theme-relearn"
uglyURLS = false
metaDataFormat = "yaml"
# required for official documentation served from subfolder
relativeURLs = false

googleAnalytics = 'G-T39HDMPC30'
disqusShortname = 'asfaqs'

[Params]
   editURL = "https://asfaqs.github.io/"
   description = "Academia Sinica FAQ Project"
   author = "ITs"
   alwaysopen = true
   showVisitedLinks = false
   disableSearch = true  #false  關閉搜尋
   disableSearchHiddenPages = false
   #collapsibleMenu = true
   disableBreadcrumb = false
   disableNextPrev = true
   disableLandingPageButton = true
   disableSeoHiddenPages = true
   disableMermaid = false
   #customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
   titleSeparator = "::"
[Params.socialshare]
  facebook = true
  linkedin = true
  twitter = true
  whatsapp = true
  email = true

[taxonomies]
  category = "categories"
  tag = "tags"
  level = "levels"
  author = "authors"

[outputs]
  home = ["HTML", "RSS", "SEARCH", "SEARCHPAGE"]
  section = ["HTML", "RSS", "PRINT" ]
  page = ["HTML", "RSS", "SEARCH", "PRINT"]

[module]
  [[module.mounts]]
    source = 'archetypes'
    target = 'archetypes'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'

  # Language dependend settings:
  # Use case https://gohugo.io/content-management/multilingual/#translation-by-filename
  [[module.mounts]]
    source = 'content'
    target = 'content'
  # Use case https://gohugo.io/content-management/multilingual/#translation-by-content-directory
  #[[module.mounts]]
  #  lang = 'en'
  #  source = 'content/en'
  #  target = 'content'
  #[[module.mounts]]
  #  lang = 'pir'
  #  source = 'content/pir'
  #  target = 'content'

  [[module.mounts]]
    source = 'data'
    target = 'data'
  [[module.mounts]]
    source = 'i18n'
    target = 'i18n'
  [[module.mounts]]
    source = '../images'
    target = 'static/images'
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'static'
    target = 'static'

[Languages]
[Languages.ja]
title = "人々のためのパブリック・インターネット・オブ・シングス(Civil IoT Taiwan)"
weight = 4
languageName = "日本語"
landingPageURL = "/"
landingPageName = "<i class='fas fa-home'></i> Home"

[Languages.zh-tw]
   title = "中央研究院 FAQ 首頁"
   weight = 1
   languageName = "中文"
   landingPageURL = "/"
   landingPageName = "<i class='fas fa-home'></i> 首頁"

[Languages.en]
   title = 'Academia Sinica FAQ'
   weight = 2
   languageName = "English"
   landingPageURL = "/"
   landingPageName = "<i class='fas fa-home'></i> Home"

[Languages.fr]
   title = "FAQ de l'Académie Sinica"
   weight = 3
   languageName = "Français"
   landingPageURL = "/"
   landingPageName = "<i class='fas fa-home'></i> Maison"
